// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLhlHupGbjq45rc7PFJGWSF4hO1r7CAI',
    appId: '1:217723689092:web:67d24df2e378fb3e954ad1',
    messagingSenderId: '217723689092',
    projectId: 'flutter-chat-app-4fc22',
    authDomain: 'flutter-chat-app-4fc22.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4fc22.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUeoAylQQBFM73HP7VeCDmpAghtUNykz8',
    appId: '1:217723689092:android:4437e3305c7cef02954ad1',
    messagingSenderId: '217723689092',
    projectId: 'flutter-chat-app-4fc22',
    storageBucket: 'flutter-chat-app-4fc22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBUQQK5Bjq6EdNNRbbXFEJe8lew0ZKCX8',
    appId: '1:217723689092:ios:6dddebe913a98aeb954ad1',
    messagingSenderId: '217723689092',
    projectId: 'flutter-chat-app-4fc22',
    storageBucket: 'flutter-chat-app-4fc22.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBUQQK5Bjq6EdNNRbbXFEJe8lew0ZKCX8',
    appId: '1:217723689092:ios:6dddebe913a98aeb954ad1',
    messagingSenderId: '217723689092',
    projectId: 'flutter-chat-app-4fc22',
    storageBucket: 'flutter-chat-app-4fc22.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHLhlHupGbjq45rc7PFJGWSF4hO1r7CAI',
    appId: '1:217723689092:web:c4b564da4f25989e954ad1',
    messagingSenderId: '217723689092',
    projectId: 'flutter-chat-app-4fc22',
    authDomain: 'flutter-chat-app-4fc22.firebaseapp.com',
    storageBucket: 'flutter-chat-app-4fc22.firebasestorage.app',
  );
}